name: GuildRoyale
version: '1.0.0-SNAPSHOT'
main: me.usainsrht.guildroyale.core.GuildRoyalePlugin
bootstrapper: bootstrap.me.usainsrht.guildroyale.core.GuildRoyaleBootstrap
api-version: '26'
description: A modern Minecraft guilds plugin with Folia support
authors:
  - GuildRoyale

soft-depend:
  - PlaceholderAPI
  - Vault
