name: GuildRoyale
version: '${project.version}'
main: me.usainsrht.guildroyale.core.GuildRoyalePlugin
loader: me.usainsrht.guildroyale.core.bootstrap.GuildRoyaleLoader
bootstrapper: me.usainsrht.guildroyale.core.bootstrap.GuildRoyaleBootstrap
api-version: '1.21'
description: A modern Minecraft guilds plugin with Folia support
folia-supported: true
authors:
  - UsainSrht

dependencies:
  server:
    Vault:
      required: true
      load: BEFORE
      join-classpath: true
    PlaceholderAPI:
      required: false
      load: BEFORE
      join-classpath: true
    MiniPlaceholders:
      required: false
      load: BEFORE
      join-classpath: true
