name: GuildRoyale
version: '1.0.0-SNAPSHOT'
main: me.usainsrht.guildroyale.core.GuildRoyalePlugin
loader: me.usainsrht.guildroyale.core.bootstrap.GuildRoyaleLoader
bootstrapper: me.usainsrht.guildroyale.core.bootstrap.GuildRoyaleBootstrap
api-version: '1.21'
description: A modern Minecraft guilds plugin with Folia support
folia-supported: true
authors:
  - GuildRoyale

soft-depend:
  - PlaceholderAPI
  - Vault
